# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start -p ${PORT:-3000}"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"