analyzed_at: '2025-10-03T13:20:55.891Z'
database_url: https://rtwigjwqufozqfwozpvo.supabase.co
tables: []
views: []
functions: []
enums: []
total_tables: 0
total_rows: 0
orphaned_tables: []
missing_rls_tables: []
recommendations: []
