openapi: 3.0.0
info:
  title: Tenant Admin API
  version: 1.0.0
  description: Tenant administrator endpoints for member management

paths:
  /api/tenant/members:
    get:
      summary: List tenant members
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [active, pending, deactivated]
        - name: role
          in: query
          schema:
            type: string
            enum: [member, tenant_admin]
      responses:
        200:
          description: List of members
          content:
            application/json:
              schema:
                type: object
                properties:
                  members:
                    type: array
                    items:
                      $ref: '#/components/schemas/MemberWithUser'
                  total:
                    type: integer

  /api/tenant/members/{memberId}:
    patch:
      summary: Update member role/status
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [member, tenant_admin]
                status:
                  type: string
                  enum: [active, deactivated]
      responses:
        200:
          description: Member updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberWithUser'
        403:
          description: Cannot modify own role

    delete:
      summary: Remove member from tenant
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: memberId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Member removed
        403:
          description: Cannot remove self or last admin

  /api/tenant/invitations:
    get:
      summary: List pending invitations
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, accepted, expired, cancelled]
            default: pending
      responses:
        200:
          description: List of invitations
          content:
            application/json:
              schema:
                type: object
                properties:
                  invitations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Invitation'

    post:
      summary: Create invitation
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, role]
              properties:
                email:
                  type: string
                  format: email
                role:
                  type: string
                  enum: [member, tenant_admin]
                expiresIn:
                  type: integer
                  description: Hours until expiration
                  default: 168
                  minimum: 1
                  maximum: 720
      responses:
        201:
          description: Invitation created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
        409:
          description: User already member or invited

  /api/tenant/invitations/{invitationId}:
    delete:
      summary: Cancel invitation
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: invitationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Invitation cancelled

  /api/tenant/requests:
    get:
      summary: List join requests
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of pending requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/JoinRequest'

  /api/tenant/requests/{requestId}/approve:
    post:
      summary: Approve join request
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
                  enum: [member, tenant_admin]
                  default: member
      responses:
        200:
          description: Request approved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemberWithUser'

  /api/tenant/requests/{requestId}/reject:
    post:
      summary: Reject join request
      tags: [Tenant Admin]
      security:
        - bearerAuth: []
      parameters:
        - name: requestId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        204:
          description: Request rejected

components:
  schemas:
    MemberWithUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        role:
          type: string
          enum: [member, tenant_admin]
        status:
          type: string
          enum: [active, pending, deactivated]
        joinedAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        user:
          type: object
          properties:
            email:
              type: string
              format: email
            name:
              type: string
            avatarUrl:
              type: string

    Invitation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        role:
          type: string
          enum: [member, tenant_admin]
        status:
          type: string
          enum: [pending, accepted, expired, cancelled]
        expiresAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: object
          properties:
            name:
              type: string
            email:
              type: string

    JoinRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        requestedAt:
          type: string
          format: date-time
        user:
          type: object
          properties:
            email:
              type: string
            name:
              type: string
            currentTenant:
              type: string
              nullable: true

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Requires tenant_admin role for user's current tenant