openapi: 3.0.0
info:
  title: User Tenant API
  version: 1.0.0
  description: User endpoints for tenant membership management

paths:
  /api/user/tenants:
    get:
      summary: List user's tenants
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of user's tenants
          content:
            application/json:
              schema:
                type: object
                properties:
                  tenants:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserTenant'
                  currentTenantId:
                    type: string
                    format: uuid
                    nullable: true

  /api/user/tenant/switch:
    post:
      summary: Switch active tenant
      tags: [User]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenantId]
              properties:
                tenantId:
                  type: string
                  format: uuid
      responses:
        200:
          description: Tenant switched
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  tenant:
                    $ref: '#/components/schemas/UserTenant'
        403:
          description: User not member of tenant

  /api/user/tenant-request:
    get:
      summary: Get user's pending requests
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of pending requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/TenantRequest'

    post:
      summary: Request to join tenant
      tags: [User]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [tenantSlug]
              properties:
                tenantSlug:
                  type: string
                  pattern: '^[a-z0-9-]{3,50}$'
                message:
                  type: string
                  maxLength: 500
                  description: Optional message to tenant admin
      responses:
        201:
          description: Request created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantRequest'
        404:
          description: Tenant not found
        409:
          description: Already member or request pending

  /api/user/invitations:
    get:
      summary: Get invitations for user
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        200:
          description: List of invitations
          content:
            application/json:
              schema:
                type: object
                properties:
                  invitations:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserInvitation'

  /api/user/invitations/{token}/accept:
    post:
      summary: Accept invitation
      tags: [User]
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Invitation accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  tenant:
                    $ref: '#/components/schemas/UserTenant'
        400:
          description: Invalid or expired token
        401:
          description: Authentication required
        409:
          description: Already member of tenant

  /api/user/tenant/leave:
    post:
      summary: Leave current tenant
      tags: [User]
      security:
        - bearerAuth: []
      responses:
        204:
          description: Left tenant successfully
        403:
          description: Cannot leave - last admin

components:
  schemas:
    UserTenant:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        slug:
          type: string
        role:
          type: string
          enum: [member, tenant_admin]
        status:
          type: string
          enum: [active, pending]
        joinedAt:
          type: string
          format: date-time
          nullable: true

    TenantRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tenantId:
          type: string
          format: uuid
        tenantName:
          type: string
        tenantSlug:
          type: string
        status:
          type: string
          enum: [pending, approved, rejected]
        requestedAt:
          type: string
          format: date-time
        message:
          type: string
          nullable: true

    UserInvitation:
      type: object
      properties:
        id:
          type: string
          format: uuid
        tenantName:
          type: string
        tenantSlug:
          type: string
        role:
          type: string
          enum: [member, tenant_admin]
        expiresAt:
          type: string
          format: date-time
        invitedBy:
          type: object
          properties:
            name:
              type: string
            email:
              type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer