-- Migration: Create Control Tower Development Tables
-- Description: Creates tables for the Project Control Tower dashboard
-- These tables are prefixed with 'dev_' to separate them from production data

-- Create dev_manifest_history table
CREATE TABLE IF NOT EXISTS public.dev_manifest_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    manifest_content TEXT NOT NULL,
    file_count INTEGER NOT NULL,
    generated_by UUID REFERENCES auth.users(id) ON DELETE SET NULL
);

-- Create index for faster queries on created_at
CREATE INDEX idx_dev_manifest_history_created_at ON public.dev_manifest_history(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.dev_manifest_history ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Only developers can view manifest history
CREATE POLICY "Developers can view manifest history" ON public.dev_manifest_history
    FOR SELECT
    USING (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    );

-- RLS Policy: Only developers can insert manifest history
CREATE POLICY "Developers can insert manifest history" ON public.dev_manifest_history
    FOR INSERT
    WITH CHECK (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    );

-- Create dev_project_standards table
CREATE TABLE IF NOT EXISTS public.dev_project_standards (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    document_title TEXT NOT NULL,
    document_content TEXT NOT NULL,
    version TEXT NOT NULL,
    last_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Create unique constraint on document_title to prevent duplicates
CREATE UNIQUE INDEX idx_dev_project_standards_title ON public.dev_project_standards(document_title);

-- Enable Row Level Security
ALTER TABLE public.dev_project_standards ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Anyone can view project standards
CREATE POLICY "Anyone can view project standards" ON public.dev_project_standards
    FOR SELECT
    USING (true);

-- RLS Policy: Only developers can modify project standards
CREATE POLICY "Developers can insert project standards" ON public.dev_project_standards
    FOR INSERT
    WITH CHECK (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    );

CREATE POLICY "Developers can update project standards" ON public.dev_project_standards
    FOR UPDATE
    USING (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    )
    WITH CHECK (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    );

CREATE POLICY "Developers can delete project standards" ON public.dev_project_standards
    FOR DELETE
    USING (
        auth.uid() IN (
            SELECT id FROM auth.users 
            WHERE raw_user_meta_data->>'is_developer' = 'true'
        )
    );

-- Add comment descriptions for tables
COMMENT ON TABLE public.dev_manifest_history IS 'Stores historical project progress manifests generated by the Control Tower';
COMMENT ON TABLE public.dev_project_standards IS 'Stores project standards documentation for the Control Tower dashboard';